[package]
name = "rust-sock-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.4.0-beta.2"
chrono = "0.4.23"
tokio = { version = "1.25.0", features = ["full"] }